/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package classes;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author ezefranca
 */
public class TelaProtuario extends javax.swing.JFrame  {
    DefaultListModel<String> model;
    DefaultListModel<String> modelHistorico;
    ArrayList<ArrayList<String>> protuarioPaciente;
    String[] cabecalho = {"Nome", "Dia", "Atendido pelo Médico:"};
    String typeUser;
    String localPaciente;
    private String localNome;
    private ArrayList<ArrayList<String>> historicoPaciente;
    

    /**
     * Creates new form TelaProtuario
     * @param paciente
     * @param permissao
     */
    public TelaProtuario(String nome, String paciente, String permissao) {
        localNome = nome;
        typeUser = permissao;
        localPaciente = paciente;
        localNome = nome;
        Protuario protuario = new Protuario();
        protuarioPaciente = protuario.ler(paciente);
        System.out.println("Lendo protuario de " + paciente);
        initComponents();
        botaoEditar.setEnabled(false);
        jLabel1.setText("Visualizando protuário do paciente: " + paciente);
        model = new DefaultListModel<>();
        
        model.addElement("Histórico de Consultas");
        for(int i = 0; i < protuarioPaciente.size();i++){
            
            for(int j= 0; j < protuarioPaciente.get(i).size();j++){
                if(protuarioPaciente.get(i).get(0).equals(paciente)){
                    if(j == 0){
                    model.addElement(" ");
                    model.addElement("Atendimento:");
                    model.addElement("--------------");
                    }
                    model.addElement(cabecalho[j] + " " + protuarioPaciente.get(i).get(j));
                }
            }
        }
        jHistoricoConsultas.setModel(model);
        jHistoricoConsultas.setSelectedIndex(0);
        
        
        Historico historico = new Historico();
        historicoPaciente = historico.ler(paciente);
        botaoEditar.setEnabled(false);
        jLabel2.setText("Visualizando histórico do paciente: " + paciente);
        modelHistorico = new DefaultListModel<>();
        
        modelHistorico.addElement("Histórico Médico");
         modelHistorico.addElement("Nome" + " | " + "Pressão" + " | " + "Peso" + " | " + "Informações");
                   
        for(int i = 0; i < historicoPaciente.size();i++){
            for(int j= 0; j < historicoPaciente.get(i).size();j++){
                if(historicoPaciente.get(i).get(0).equals(paciente)){
                    System.out.println("cururu entrou no if");
                    
                    modelHistorico.addElement(historicoPaciente.get(i).get(0) + " | " + historicoPaciente.get(i).get(1) + " | " + historicoPaciente.get(i).get(2) + " | " +historicoPaciente.get(i).get(3));
                   
                    break;
                }
            }
        }
        jHistoricoMedico.setModel(modelHistorico);
        jHistoricoMedico.setSelectedIndex(0);
        
        
    }

    private TelaProtuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jHistoricoConsultas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jHistoricoMedico = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jHistoricoConsultas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jHistoricoConsultas);

        jLabel1.setText("jLabel1");

        jButton1.setText("Voltar para a tela principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");

        jHistoricoMedico.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jHistoricoMedico);

        jLabel2.setText("jLabel2");

        jMenu2.setText("Protuário");

        jMenu5.setText("Sobre");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(botaoEditar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(291, 291, 291))
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(botaoEditar)
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CSVAcesso acesso = new CSVAcesso("cadastro.csv", "true");
        acesso.parse();
        String userDados[] = {typeUser, localNome};
        switch (userDados[0]) {
            case "Paciente":
                TelaPaciente paciente = new TelaPaciente(userDados[1], acesso.pegarMedicos(), acesso.pegarDentistas(), userDados[0]);
                paciente.setDefaultCloseOperation(TelaInicial.EXIT_ON_CLOSE);
                this.setVisible(false);
                paciente.setVisible(true);
                break;
            case "Medico":
                TelaMedico medico = new TelaMedico(userDados[1], acesso.pegarPacientes(), userDados[0]);
                //medico.setDefaultCloseOperation(TelaInicial.EXIT_ON_CLOSE);
                medico.pack();
                this.setVisible(false);
                medico.setVisible(true);
                break;
            case "Dentista":
                TelaDentista dentista = new TelaDentista(userDados[1], acesso.pegarPacientes(), userDados[0]);
                //dentista.setDefaultCloseOperation(TelaInicial.EXIT_ON_CLOSE);
                dentista.pack();
                this.setVisible(false);
                dentista.setVisible(true);
                break;
            case "Enfermeiro":
                TelaEnfermeiro enfermeiro = new TelaEnfermeiro(userDados[1], acesso.pegarPacientes(), userDados[0]);
                //enfermeiro.setDefaultCloseOperation(TelaInicial.EXIT_ON_CLOSE);
                enfermeiro.pack();
                this.setVisible(false);
                enfermeiro.setVisible(true);
                break;
            default:
                System.out.println("Usuario nao possui um tipo correto");
                break;
        }         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        System.out.println("apertou o menu");
    }//GEN-LAST:event_jMenu5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProtuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaProtuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton jButton1;
    private javax.swing.JList jHistoricoConsultas;
    private javax.swing.JList jHistoricoMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
