/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package classes;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author ezefranca
 */
public class TelaEnfermeiro extends javax.swing.JFrame {

    private String localNome;
    private String typeUser;
    private DefaultListModel<String> model;
    private ArrayList<ArrayList<String>> agendaTotal;
    private DefaultListModel<String> modelLista1;
    private boolean temConsulta;
   

    /**
     * Creates new form TelaEnfermeiro
     *
     * @param nome
     * @param pacientes
     * @param permissao
     */
    public TelaEnfermeiro(String nome, ArrayList<String> pacientes, String permissao) {
        localNome = nome;
        typeUser = permissao;
        localNome = nome;
        temConsulta = false;
        // Protuario protuario = new Protuario();
        initComponents();
        
        modelLista1 = new DefaultListModel<>();
        for (String paciente : pacientes) {
            modelLista1.addElement(paciente);
        }
        listaPacientes.setModel(modelLista1);
        listaPacientes.setSelectedIndex(0);
        
        System.out.println("Lendo consultas de " + nome);
        
        model = new DefaultListModel<>();
        
        CSVAcesso ler = new CSVAcesso("agenda.csv", "true");
        ler.parse();
        agendaTotal = ler.retornarTudo();
        
        model.addElement("Consultas Médicas marcadas");
        for (ArrayList<String> agendaPaciente1 : agendaTotal) {
            for (int j = 0; j < agendaPaciente1.size(); j++) {
                if (agendaPaciente1.get(3).equals(listaPacientes.getSelectedValue().toString())) {
                    if (j == 0 && temConsulta == false) {
                        //model.addElement(" ");
                        //model.addElement("Consulta:");
                        model.addElement("Tem consultas marcadas");
                        temConsulta = true;
                        break;
                    }
                    //model.addElement(agendaPaciente1.get(j));
                }
            }
        }
        if (temConsulta == false) {
              //model.addElement(" ");
            //model.addElement("Consulta:");
            model.addElement("Paciente não Tem consultas marcadas");            
        }
        listaConsultas.setModel(model);
        btnSalvar.setVisible(temConsulta);
    }
    
    private TelaEnfermeiro() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSaudacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaConsultas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPacientes = new javax.swing.JList();
        campoPressao = new javax.swing.JTextField();
        campoPeso = new javax.swing.JTextField();
        labelMenu = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        labelPressao = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        campoInformacoes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        labelSaudacao.setText("Seja bem vindo Enfermeiro(a) *****");

        listaConsultas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaConsultas);

        listaPacientes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPacientesMouseClicked(evt);
            }
        });
        listaPacientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPacientesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaPacientes);

        campoPressao.setToolTipText("");
        campoPressao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        labelMenu.setText("Adicione as informações de peso e pressão");

        labelPeso.setText("Peso");

        labelPressao.setText("Pressão");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        campoInformacoes.setToolTipText("Informaçoes adicionais");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(labelPeso)
                                                .addGap(66, 66, 66))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelPressao)
                                            .addComponent(campoPressao, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(btnSalvar)))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelSaudacao)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(labelMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPeso)
                    .addComponent(labelPressao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(campoInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaPacientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPacientesValueChanged
//        model.addElement("Consultas Médicas marcadas");
//        for (ArrayList<String> agendaPaciente1 : agendaTotal) {
//            for (int j = 0; j < agendaPaciente1.size(); j++) {
//                if (agendaPaciente1.get(3).equals(jList2.getSelectedValue().toString())) {
//                    if(j == 0){
//                        model.addElement(" ");
//                        model.addElement("Consulta:");
//                        model.addElement("--------------");
//                    }
//                    model.addElement(agendaPaciente1.get(j));
//                }
//            }
//        }
//        jListaConsultas.setModel(model);
//        jListaConsultas.setSelectedIndex(0);
    }//GEN-LAST:event_listaPacientesValueChanged

    private void listaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPacientesMouseClicked
        DefaultListModel listModel = (DefaultListModel) listaConsultas.getModel();
        listModel.removeAllElements();
        temConsulta = false;
        
        model.addElement("Consultas Médicas marcadas");
        for (ArrayList<String> agendaPaciente1 : agendaTotal) {
            for (int j = 0; j < agendaPaciente1.size(); j++) {
                if (agendaPaciente1.get(3).equals(listaPacientes.getSelectedValue().toString())) {
                    if (j == 0 && temConsulta == false) {
                        //model.addElement(" ");
                        //model.addElement("Consulta:");
                        model.addElement("Tem consultas marcadas");
                        temConsulta = true;
                        break;
                    }
                    //model.addElement(agendaPaciente1.get(j));
                }
            }
        }
        if (temConsulta == false) {
              //model.addElement(" ");
            //model.addElement("Consulta:");
            model.addElement("Paciente não Tem consultas marcadas");            
        }
        listaConsultas.setModel(model);
        //jListaConsultas.setSelectedIndex(0);
        btnSalvar.setVisible(temConsulta);
    }//GEN-LAST:event_listaPacientesMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Boolean ocupado = false;
        Historico salvar = new Historico();
        String peso = campoPeso.getText();
        String pressao = campoPressao.getText();
        String informacoes = campoInformacoes.getText();
        String paciente = listaPacientes.getSelectedValue().toString();
        
//        CSVAcesso ler = new CSVAcesso("agenda.csv", "true");
//        ler.parse();
        
        salvar.gravar(paciente, pressao, peso, informacoes);
        campoPeso.setText("");
        campoInformacoes.setText("");
        campoPressao.setText("");
        System.out.println("Informacoes Salvas");
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaEnfermeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField campoInformacoes;
    private javax.swing.JTextField campoPeso;
    private javax.swing.JTextField campoPressao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelPressao;
    private javax.swing.JLabel labelSaudacao;
    private javax.swing.JList listaConsultas;
    private javax.swing.JList listaPacientes;
    // End of variables declaration//GEN-END:variables
}
